server:
  port: 8080

logging:
  level:
    cn.kangpb.dao: debug

spring:
  datasource:
    url: jdbc:mysql://129.204.15.237:3306/ssms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 13148899
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp